"""Load Spanish vocabulary from the pre-built JSON file.

Reads ``data/spanish_top10000.json`` (generated by
``scripts/build_spanish_vocab.py``), inserts the top N words
into a Rembrandt database, and runs a short interactive quiz.

Usage::

    uv run python examples/06_load_spanish_vocab.py
"""

import json
from pathlib import Path

from rembrandt import Database, ExerciseType, Session

_ROOT = Path(__file__).resolve().parent.parent
_VOCAB_PATH = _ROOT / "data" / "spanish_top10000.json"
_TOP_N = 500


def load_vocab(
    db: Database,
    path: Path = _VOCAB_PATH,
    limit: int = _TOP_N,
) -> int:
    """Insert the top `limit` Spanish words into `db`.

    Words are inserted in frequency order so that
    ``select_words()`` introduces the most common words
    first.

    :param db: Target database.
    :param path: Path to the vocabulary JSON file.
    :param limit: Number of words to load.
    :return: Number of words inserted.
    """
    with open(path, encoding="utf-8") as fh:
        entries = json.load(fh)

    words = [
        ("es", "en", entry["word"], entry["definition"])
        for entry in entries[:limit]
    ]
    db.add_words(words)
    return len(words)


def main() -> None:
    if not _VOCAB_PATH.exists():
        print(
            f"Vocabulary file not found: {_VOCAB_PATH}\n"
            "Run the build script first:\n"
            "  uv run python scripts/build_spanish_vocab.py"
        )
        return

    db = Database(":memory:")
    count = load_vocab(db)
    print(f"Loaded {count} Spanish words.\n")

    session = Session(
        db=db,
        user_id="demo",
        language_from="es",
        language_to="en",
    )

    print("=== Spanish Vocabulary Quiz ===")
    print("Type your answer (or 'q' to quit).\n")

    correct = 0
    total = 0

    while True:
        exercise = session.next_exercise()
        if exercise is None:
            break

        total += 1
        etype = exercise.exercise_type

        print(f"--- Question {total} ---")
        print(f"What does '{exercise.word.word_from}' mean?")

        if etype == ExerciseType.MULTIPLE_CHOICE:
            for idx, opt in enumerate(exercise.options, 1):
                print(f"  {idx}. {opt}")

        answer = input("> ").strip()
        if answer.lower() == "q":
            total -= 1
            break

        result = session.answer(answer)
        if result.correct:
            correct += 1
            print("Correct!\n")
        else:
            print(f"Wrong — expected: {result.expected}\n")

    if total > 0:
        pct = correct / total * 100
        print(f"Score: {correct}/{total} ({pct:.0f}%)")

    db.close()


if __name__ == "__main__":
    main()
